/*
 * configoptions_gen.go
 *
 * GENERATED by analyzer/gen/generate_configoptions.py from
 * common/configOptions.ts and common/diagnosticRules.ts. Do not edit.
 *
 * Run `make generate` to regenerate.
 */

package analyzer

// DiagnosticRule corresponds to the enum of the same name in
// common/diagnosticRules.ts. Every member's value equals its name, so the
// string is both the config key and the rule identity.
type DiagnosticRule = string

const (
	DiagnosticRuleStrictListInference                 DiagnosticRule = "strictListInference"
	DiagnosticRuleStrictSetInference                  DiagnosticRule = "strictSetInference"
	DiagnosticRuleStrictDictionaryInference           DiagnosticRule = "strictDictionaryInference"
	DiagnosticRuleAnalyzeUnannotatedFunctions         DiagnosticRule = "analyzeUnannotatedFunctions"
	DiagnosticRuleStrictParameterNoneValue            DiagnosticRule = "strictParameterNoneValue"
	DiagnosticRuleEnableExperimentalFeatures          DiagnosticRule = "enableExperimentalFeatures"
	DiagnosticRuleEnableTypeIgnoreComments            DiagnosticRule = "enableTypeIgnoreComments"
	DiagnosticRuleEnableReachabilityAnalysis          DiagnosticRule = "enableReachabilityAnalysis"
	DiagnosticRuleDeprecateTypingAliases              DiagnosticRule = "deprecateTypingAliases"
	DiagnosticRuleDisableBytesTypePromotions          DiagnosticRule = "disableBytesTypePromotions"
	DiagnosticRuleReportGeneralTypeIssues             DiagnosticRule = "reportGeneralTypeIssues"
	DiagnosticRuleReportPropertyTypeMismatch          DiagnosticRule = "reportPropertyTypeMismatch"
	DiagnosticRuleReportFunctionMemberAccess          DiagnosticRule = "reportFunctionMemberAccess"
	DiagnosticRuleReportMissingImports                DiagnosticRule = "reportMissingImports"
	DiagnosticRuleReportMissingModuleSource           DiagnosticRule = "reportMissingModuleSource"
	DiagnosticRuleReportInvalidTypeForm               DiagnosticRule = "reportInvalidTypeForm"
	DiagnosticRuleReportMissingTypeStubs              DiagnosticRule = "reportMissingTypeStubs"
	DiagnosticRuleReportImportCycles                  DiagnosticRule = "reportImportCycles"
	DiagnosticRuleReportUnusedImport                  DiagnosticRule = "reportUnusedImport"
	DiagnosticRuleReportUnusedClass                   DiagnosticRule = "reportUnusedClass"
	DiagnosticRuleReportUnusedFunction                DiagnosticRule = "reportUnusedFunction"
	DiagnosticRuleReportUnusedVariable                DiagnosticRule = "reportUnusedVariable"
	DiagnosticRuleReportDuplicateImport               DiagnosticRule = "reportDuplicateImport"
	DiagnosticRuleReportWildcardImportFromLibrary     DiagnosticRule = "reportWildcardImportFromLibrary"
	DiagnosticRuleReportAbstractUsage                 DiagnosticRule = "reportAbstractUsage"
	DiagnosticRuleReportArgumentType                  DiagnosticRule = "reportArgumentType"
	DiagnosticRuleReportAssertTypeFailure             DiagnosticRule = "reportAssertTypeFailure"
	DiagnosticRuleReportAssignmentType                DiagnosticRule = "reportAssignmentType"
	DiagnosticRuleReportAttributeAccessIssue          DiagnosticRule = "reportAttributeAccessIssue"
	DiagnosticRuleReportCallIssue                     DiagnosticRule = "reportCallIssue"
	DiagnosticRuleReportInconsistentOverload          DiagnosticRule = "reportInconsistentOverload"
	DiagnosticRuleReportIndexIssue                    DiagnosticRule = "reportIndexIssue"
	DiagnosticRuleReportInvalidTypeArguments          DiagnosticRule = "reportInvalidTypeArguments"
	DiagnosticRuleReportNoOverloadImplementation      DiagnosticRule = "reportNoOverloadImplementation"
	DiagnosticRuleReportOperatorIssue                 DiagnosticRule = "reportOperatorIssue"
	DiagnosticRuleReportOptionalSubscript             DiagnosticRule = "reportOptionalSubscript"
	DiagnosticRuleReportOptionalMemberAccess          DiagnosticRule = "reportOptionalMemberAccess"
	DiagnosticRuleReportOptionalCall                  DiagnosticRule = "reportOptionalCall"
	DiagnosticRuleReportOptionalIterable              DiagnosticRule = "reportOptionalIterable"
	DiagnosticRuleReportOptionalContextManager        DiagnosticRule = "reportOptionalContextManager"
	DiagnosticRuleReportOptionalOperand               DiagnosticRule = "reportOptionalOperand"
	DiagnosticRuleReportRedeclaration                 DiagnosticRule = "reportRedeclaration"
	DiagnosticRuleReportReturnType                    DiagnosticRule = "reportReturnType"
	DiagnosticRuleReportTypedDictNotRequiredAccess    DiagnosticRule = "reportTypedDictNotRequiredAccess"
	DiagnosticRuleReportUntypedFunctionDecorator      DiagnosticRule = "reportUntypedFunctionDecorator"
	DiagnosticRuleReportUntypedClassDecorator         DiagnosticRule = "reportUntypedClassDecorator"
	DiagnosticRuleReportUntypedBaseClass              DiagnosticRule = "reportUntypedBaseClass"
	DiagnosticRuleReportUntypedNamedTuple             DiagnosticRule = "reportUntypedNamedTuple"
	DiagnosticRuleReportPrivateUsage                  DiagnosticRule = "reportPrivateUsage"
	DiagnosticRuleReportTypeCommentUsage              DiagnosticRule = "reportTypeCommentUsage"
	DiagnosticRuleReportPrivateImportUsage            DiagnosticRule = "reportPrivateImportUsage"
	DiagnosticRuleReportConstantRedefinition          DiagnosticRule = "reportConstantRedefinition"
	DiagnosticRuleReportDeprecated                    DiagnosticRule = "reportDeprecated"
	DiagnosticRuleReportIncompatibleMethodOverride    DiagnosticRule = "reportIncompatibleMethodOverride"
	DiagnosticRuleReportIncompatibleVariableOverride  DiagnosticRule = "reportIncompatibleVariableOverride"
	DiagnosticRuleReportInconsistentConstructor       DiagnosticRule = "reportInconsistentConstructor"
	DiagnosticRuleReportOverlappingOverload           DiagnosticRule = "reportOverlappingOverload"
	DiagnosticRuleReportPossiblyUnboundVariable       DiagnosticRule = "reportPossiblyUnboundVariable"
	DiagnosticRuleReportMissingSuperCall              DiagnosticRule = "reportMissingSuperCall"
	DiagnosticRuleReportUninitializedInstanceVariable DiagnosticRule = "reportUninitializedInstanceVariable"
	DiagnosticRuleReportInvalidStringEscapeSequence   DiagnosticRule = "reportInvalidStringEscapeSequence"
	DiagnosticRuleReportUnknownParameterType          DiagnosticRule = "reportUnknownParameterType"
	DiagnosticRuleReportUnknownArgumentType           DiagnosticRule = "reportUnknownArgumentType"
	DiagnosticRuleReportUnknownLambdaType             DiagnosticRule = "reportUnknownLambdaType"
	DiagnosticRuleReportUnknownVariableType           DiagnosticRule = "reportUnknownVariableType"
	DiagnosticRuleReportUnknownMemberType             DiagnosticRule = "reportUnknownMemberType"
	DiagnosticRuleReportMissingParameterType          DiagnosticRule = "reportMissingParameterType"
	DiagnosticRuleReportMissingTypeArgument           DiagnosticRule = "reportMissingTypeArgument"
	DiagnosticRuleReportInvalidTypeVarUse             DiagnosticRule = "reportInvalidTypeVarUse"
	DiagnosticRuleReportCallInDefaultInitializer      DiagnosticRule = "reportCallInDefaultInitializer"
	DiagnosticRuleReportUnnecessaryIsInstance         DiagnosticRule = "reportUnnecessaryIsInstance"
	DiagnosticRuleReportUnnecessaryCast               DiagnosticRule = "reportUnnecessaryCast"
	DiagnosticRuleReportUnnecessaryComparison         DiagnosticRule = "reportUnnecessaryComparison"
	DiagnosticRuleReportUnnecessaryContains           DiagnosticRule = "reportUnnecessaryContains"
	DiagnosticRuleReportAssertAlwaysTrue              DiagnosticRule = "reportAssertAlwaysTrue"
	DiagnosticRuleReportSelfClsParameterName          DiagnosticRule = "reportSelfClsParameterName"
	DiagnosticRuleReportImplicitStringConcatenation   DiagnosticRule = "reportImplicitStringConcatenation"
	DiagnosticRuleReportUndefinedVariable             DiagnosticRule = "reportUndefinedVariable"
	DiagnosticRuleReportUnboundVariable               DiagnosticRule = "reportUnboundVariable"
	DiagnosticRuleReportUnhashable                    DiagnosticRule = "reportUnhashable"
	DiagnosticRuleReportInvalidStubStatement          DiagnosticRule = "reportInvalidStubStatement"
	DiagnosticRuleReportIncompleteStub                DiagnosticRule = "reportIncompleteStub"
	DiagnosticRuleReportUnsupportedDunderAll          DiagnosticRule = "reportUnsupportedDunderAll"
	DiagnosticRuleReportUnusedCallResult              DiagnosticRule = "reportUnusedCallResult"
	DiagnosticRuleReportUnusedCoroutine               DiagnosticRule = "reportUnusedCoroutine"
	DiagnosticRuleReportUnusedExcept                  DiagnosticRule = "reportUnusedExcept"
	DiagnosticRuleReportUnusedExpression              DiagnosticRule = "reportUnusedExpression"
	DiagnosticRuleReportUnnecessaryTypeIgnoreComment  DiagnosticRule = "reportUnnecessaryTypeIgnoreComment"
	DiagnosticRuleReportMatchNotExhaustive            DiagnosticRule = "reportMatchNotExhaustive"
	DiagnosticRuleReportUnreachable                   DiagnosticRule = "reportUnreachable"
	DiagnosticRuleReportImplicitOverride              DiagnosticRule = "reportImplicitOverride"
)

// DiagnosticRuleSet corresponds to the interface of the same name.
type DiagnosticRuleSet struct {
	// Should "Unknown" types be reported as "Any"?
	PrintUnknownAsAny bool

	// Should type arguments to a generic class be omitted
	// when printed if all arguments are Unknown?
	OmitTypeArgsIfUnknown bool

	// Should parameter type be omitted if it is not annotated?
	OmitUnannotatedParamType bool

	// Indicate when a type is conditional based on a constrained
	// type variable type?
	OmitConditionalConstraint bool

	// Should Union and Optional types be printed in PEP 604 format?
	Pep604Printing bool

	// Use strict inference rules for list expressions?
	StrictListInference bool

	// Use strict inference rules for set expressions?
	StrictSetInference bool

	// Use strict inference rules for dictionary expressions?
	StrictDictionaryInference bool

	// Analyze functions and methods that have no annotations?
	AnalyzeUnannotatedFunctions bool

	// Use strict type rules for parameters assigned default of None?
	StrictParameterNoneValue bool

	// Enable experimental features that are not yet part of the
	// official Python typing spec?
	EnableExperimentalFeatures bool

	// Enable support for type: ignore comments?
	EnableTypeIgnoreComments bool

	// Use tagged hints to identify unreachable code via type analysis?
	EnableReachabilityAnalysis bool

	// Treat old typing aliases as deprecated if pythonVersion >= 3.9?
	DeprecateTypingAliases bool

	// No longer treat bytearray and memoryview as subclasses of bytes?
	DisableBytesTypePromotions bool

	// Report general type issues?
	ReportGeneralTypeIssues DiagnosticLevel

	// Report mismatch in types between property getter and setter?
	ReportPropertyTypeMismatch DiagnosticLevel

	// Report the use of unknown member accesses on function objects?
	ReportFunctionMemberAccess DiagnosticLevel

	// Report missing imports?
	ReportMissingImports DiagnosticLevel

	// Report missing imported module source files?
	ReportMissingModuleSource DiagnosticLevel

	// Report invalid type annotation forms?
	ReportInvalidTypeForm DiagnosticLevel

	// Report missing type stub files?
	ReportMissingTypeStubs DiagnosticLevel

	// Report cycles in import graph?
	ReportImportCycles DiagnosticLevel

	// Report imported symbol that is not accessed?
	ReportUnusedImport DiagnosticLevel

	// Report private class that is not accessed?
	ReportUnusedClass DiagnosticLevel

	// Report private function or method that is not accessed?
	ReportUnusedFunction DiagnosticLevel

	// Report variable that is not accessed?
	ReportUnusedVariable DiagnosticLevel

	// Report symbol or module that is imported more than once?
	ReportDuplicateImport DiagnosticLevel

	// Report use of wildcard import for non-local imports?
	ReportWildcardImportFromLibrary DiagnosticLevel

	// Report use of abstract method or variable?
	ReportAbstractUsage DiagnosticLevel

	// Report argument type incompatibilities?
	ReportArgumentType DiagnosticLevel

	// Report failure of assert_type call?
	ReportAssertTypeFailure DiagnosticLevel

	// Report type incompatibility for assignments?
	ReportAssignmentType DiagnosticLevel

	// Report issues related to attribute access expressions?
	ReportAttributeAccessIssue DiagnosticLevel

	// Report issues related to call expressions?
	ReportCallIssue DiagnosticLevel

	// Report inconsistencies with function overload signatures?
	ReportInconsistentOverload DiagnosticLevel

	// Report issues with index operations and expressions?
	ReportIndexIssue DiagnosticLevel

	// Report invalid type argument usage?
	ReportInvalidTypeArguments DiagnosticLevel

	// Report missing overloaded function implementation?
	ReportNoOverloadImplementation DiagnosticLevel

	// Report issues related to the use of unary or binary operators?
	ReportOperatorIssue DiagnosticLevel

	// Report attempts to subscript (index) an Optional type?
	ReportOptionalSubscript DiagnosticLevel

	// Report attempts to access members on a Optional type?
	ReportOptionalMemberAccess DiagnosticLevel

	// Report attempts to call a Optional type?
	ReportOptionalCall DiagnosticLevel

	// Report attempts to use an Optional type as an iterable?
	ReportOptionalIterable DiagnosticLevel

	// Report attempts to use an Optional type in a "with" statement?
	ReportOptionalContextManager DiagnosticLevel

	// Report attempts to use an Optional type in a binary or unary operation?
	ReportOptionalOperand DiagnosticLevel

	// Report attempts to redeclare the type of a symbol?
	ReportRedeclaration DiagnosticLevel

	// Report return type mismatches?
	ReportReturnType DiagnosticLevel

	// Report accesses to non-required TypedDict fields?
	ReportTypedDictNotRequiredAccess DiagnosticLevel

	// Report untyped function decorators that obscure the function type?
	ReportUntypedFunctionDecorator DiagnosticLevel

	// Report untyped class decorators that obscure the class type?
	ReportUntypedClassDecorator DiagnosticLevel

	// Report untyped base class that obscure the class type?
	ReportUntypedBaseClass DiagnosticLevel

	// Report use of untyped namedtuple factory method?
	ReportUntypedNamedTuple DiagnosticLevel

	// Report usage of private variables and functions outside of
	// the owning class or module?
	ReportPrivateUsage DiagnosticLevel

	// Report usage of deprecated type comments.
	ReportTypeCommentUsage DiagnosticLevel

	// Report usage of an import from a py.typed module that is
	// not meant to be re-exported from that module.
	ReportPrivateImportUsage DiagnosticLevel

	// Report attempts to redefine variables that are in all-caps.
	ReportConstantRedefinition DiagnosticLevel

	// Report use of deprecated classes or functions.
	ReportDeprecated DiagnosticLevel

	// Report usage of method override that is incompatible with
	// the base class method of the same name?
	ReportIncompatibleMethodOverride DiagnosticLevel

	// Report usage of variable override that is incompatible with
	// the base class symbol of the same name?
	ReportIncompatibleVariableOverride DiagnosticLevel

	// Report inconsistencies between __init__ and __new__ signatures.
	ReportInconsistentConstructor DiagnosticLevel

	// Report function overloads that overlap in signature but have
	// incompatible return types.
	ReportOverlappingOverload DiagnosticLevel

	// Report usage of possibly unbound variables.
	ReportPossiblyUnboundVariable DiagnosticLevel

	// Report failure to call super().__init__() in __init__ method.
	ReportMissingSuperCall DiagnosticLevel

	// Report instance variables that are not initialized within
	// the constructor.
	ReportUninitializedInstanceVariable DiagnosticLevel

	// Report usage of invalid escape sequences in string literals?
	ReportInvalidStringEscapeSequence DiagnosticLevel

	// Report usage of unknown input or return parameters for functions?
	ReportUnknownParameterType DiagnosticLevel

	// Report usage of unknown arguments for function calls?
	ReportUnknownArgumentType DiagnosticLevel

	// Report usage of unknown input or return parameters for lambdas?
	ReportUnknownLambdaType DiagnosticLevel

	// Report usage of unknown input or return parameters?
	ReportUnknownVariableType DiagnosticLevel

	// Report usage of unknown input or return parameters?
	ReportUnknownMemberType DiagnosticLevel

	// Report input parameters that are missing type annotations?
	ReportMissingParameterType DiagnosticLevel

	// Report usage of generic class without explicit type arguments?
	ReportMissingTypeArgument DiagnosticLevel

	// Report improper usage of type variables within function signatures?
	ReportInvalidTypeVarUse DiagnosticLevel

	// Report usage of function call within default value
	// initialization expression?
	ReportCallInDefaultInitializer DiagnosticLevel

	// Report calls to isinstance or issubclass that are statically determined
	// to always be true.
	ReportUnnecessaryIsInstance DiagnosticLevel

	// Report calls to cast that are statically determined
	// to always unnecessary.
	ReportUnnecessaryCast DiagnosticLevel

	// Report == or != operators that always evaluate to True or False.
	ReportUnnecessaryComparison DiagnosticLevel

	// Report 'in' operations that always evaluate to True or False.
	ReportUnnecessaryContains DiagnosticLevel

	// Report assert expressions that will always evaluate to true.
	ReportAssertAlwaysTrue DiagnosticLevel

	// Report when "self" or "cls" parameter is missing or is misnamed.
	ReportSelfClsParameterName DiagnosticLevel

	// Report implicit concatenation of string literals.
	ReportImplicitStringConcatenation DiagnosticLevel

	// Report usage of undefined variables.
	ReportUndefinedVariable DiagnosticLevel

	// Report usage of unbound variables.
	ReportUnboundVariable DiagnosticLevel

	// Report use of unhashable type in a dictionary.
	ReportUnhashable DiagnosticLevel

	// Report statements that are syntactically correct but
	// have no semantic meaning within a type stub file.
	ReportInvalidStubStatement DiagnosticLevel

	// Report usage of __getattr__ at the module level in a stub.
	ReportIncompleteStub DiagnosticLevel

	// Report operations on __all__ symbol that are not supported
	// by a static type checker.
	ReportUnsupportedDunderAll DiagnosticLevel

	// Report cases where a call expression's return result is not
	// None and is not used in any way.
	ReportUnusedCallResult DiagnosticLevel

	// Report cases where a call expression's return result is Coroutine
	// and is not used in any way.
	ReportUnusedCoroutine DiagnosticLevel

	// Report except clause that is unreachable.
	ReportUnusedExcept DiagnosticLevel

	// Report cases where a simple expression result is not used in any way.
	ReportUnusedExpression DiagnosticLevel

	// Report cases where the removal of a "# type: ignore" or "# pyright: ignore"
	// comment would have no effect.
	ReportUnnecessaryTypeIgnoreComment DiagnosticLevel

	// Report cases where the a "match" statement is not exhaustive in
	// covering all possible cases.
	ReportMatchNotExhaustive DiagnosticLevel

	// Report code that is determined to be unreachable via type analysis.
	ReportUnreachable DiagnosticLevel

	// Report missing @override decorator.
	ReportImplicitOverride DiagnosticLevel
}

// CloneDiagnosticRuleSet corresponds to cloneDiagnosticRuleSet. The original
// makes a shallow copy with Object.assign; every field is a scalar, so a Go
// struct copy is the same thing.
func CloneDiagnosticRuleSet(diagSettings *DiagnosticRuleSet) *DiagnosticRuleSet {
	clone := *diagSettings
	return &clone
}

// diagnosticRuleBoolFields maps a rule name to the bool field it names.
// It stands in for the original's `(ruleSet as any)[ruleName]`.
var diagnosticRuleBoolFields = map[DiagnosticRule]func(*DiagnosticRuleSet) *bool{
	DiagnosticRuleStrictListInference:         func(rs *DiagnosticRuleSet) *bool { return &rs.StrictListInference },
	DiagnosticRuleStrictSetInference:          func(rs *DiagnosticRuleSet) *bool { return &rs.StrictSetInference },
	DiagnosticRuleStrictDictionaryInference:   func(rs *DiagnosticRuleSet) *bool { return &rs.StrictDictionaryInference },
	DiagnosticRuleAnalyzeUnannotatedFunctions: func(rs *DiagnosticRuleSet) *bool { return &rs.AnalyzeUnannotatedFunctions },
	DiagnosticRuleStrictParameterNoneValue:    func(rs *DiagnosticRuleSet) *bool { return &rs.StrictParameterNoneValue },
	DiagnosticRuleEnableExperimentalFeatures:  func(rs *DiagnosticRuleSet) *bool { return &rs.EnableExperimentalFeatures },
	DiagnosticRuleEnableTypeIgnoreComments:    func(rs *DiagnosticRuleSet) *bool { return &rs.EnableTypeIgnoreComments },
	DiagnosticRuleEnableReachabilityAnalysis:  func(rs *DiagnosticRuleSet) *bool { return &rs.EnableReachabilityAnalysis },
	DiagnosticRuleDeprecateTypingAliases:      func(rs *DiagnosticRuleSet) *bool { return &rs.DeprecateTypingAliases },
	DiagnosticRuleDisableBytesTypePromotions:  func(rs *DiagnosticRuleSet) *bool { return &rs.DisableBytesTypePromotions },
}

// diagnosticRuleLevelFields maps a rule name to the DiagnosticLevel field it
// names. It stands in for the original's `(ruleSet as any)[ruleName]`.
var diagnosticRuleLevelFields = map[DiagnosticRule]func(*DiagnosticRuleSet) *DiagnosticLevel{
	DiagnosticRuleReportGeneralTypeIssues:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportGeneralTypeIssues },
	DiagnosticRuleReportPropertyTypeMismatch:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportPropertyTypeMismatch },
	DiagnosticRuleReportFunctionMemberAccess:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportFunctionMemberAccess },
	DiagnosticRuleReportMissingImports:                func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMissingImports },
	DiagnosticRuleReportMissingModuleSource:           func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMissingModuleSource },
	DiagnosticRuleReportInvalidTypeForm:               func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInvalidTypeForm },
	DiagnosticRuleReportMissingTypeStubs:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMissingTypeStubs },
	DiagnosticRuleReportImportCycles:                  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportImportCycles },
	DiagnosticRuleReportUnusedImport:                  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedImport },
	DiagnosticRuleReportUnusedClass:                   func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedClass },
	DiagnosticRuleReportUnusedFunction:                func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedFunction },
	DiagnosticRuleReportUnusedVariable:                func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedVariable },
	DiagnosticRuleReportDuplicateImport:               func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportDuplicateImport },
	DiagnosticRuleReportWildcardImportFromLibrary:     func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportWildcardImportFromLibrary },
	DiagnosticRuleReportAbstractUsage:                 func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportAbstractUsage },
	DiagnosticRuleReportArgumentType:                  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportArgumentType },
	DiagnosticRuleReportAssertTypeFailure:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportAssertTypeFailure },
	DiagnosticRuleReportAssignmentType:                func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportAssignmentType },
	DiagnosticRuleReportAttributeAccessIssue:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportAttributeAccessIssue },
	DiagnosticRuleReportCallIssue:                     func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportCallIssue },
	DiagnosticRuleReportInconsistentOverload:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInconsistentOverload },
	DiagnosticRuleReportIndexIssue:                    func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportIndexIssue },
	DiagnosticRuleReportInvalidTypeArguments:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInvalidTypeArguments },
	DiagnosticRuleReportNoOverloadImplementation:      func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportNoOverloadImplementation },
	DiagnosticRuleReportOperatorIssue:                 func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOperatorIssue },
	DiagnosticRuleReportOptionalSubscript:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOptionalSubscript },
	DiagnosticRuleReportOptionalMemberAccess:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOptionalMemberAccess },
	DiagnosticRuleReportOptionalCall:                  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOptionalCall },
	DiagnosticRuleReportOptionalIterable:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOptionalIterable },
	DiagnosticRuleReportOptionalContextManager:        func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOptionalContextManager },
	DiagnosticRuleReportOptionalOperand:               func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOptionalOperand },
	DiagnosticRuleReportRedeclaration:                 func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportRedeclaration },
	DiagnosticRuleReportReturnType:                    func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportReturnType },
	DiagnosticRuleReportTypedDictNotRequiredAccess:    func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportTypedDictNotRequiredAccess },
	DiagnosticRuleReportUntypedFunctionDecorator:      func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUntypedFunctionDecorator },
	DiagnosticRuleReportUntypedClassDecorator:         func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUntypedClassDecorator },
	DiagnosticRuleReportUntypedBaseClass:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUntypedBaseClass },
	DiagnosticRuleReportUntypedNamedTuple:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUntypedNamedTuple },
	DiagnosticRuleReportPrivateUsage:                  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportPrivateUsage },
	DiagnosticRuleReportTypeCommentUsage:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportTypeCommentUsage },
	DiagnosticRuleReportPrivateImportUsage:            func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportPrivateImportUsage },
	DiagnosticRuleReportConstantRedefinition:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportConstantRedefinition },
	DiagnosticRuleReportDeprecated:                    func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportDeprecated },
	DiagnosticRuleReportIncompatibleMethodOverride:    func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportIncompatibleMethodOverride },
	DiagnosticRuleReportIncompatibleVariableOverride:  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportIncompatibleVariableOverride },
	DiagnosticRuleReportInconsistentConstructor:       func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInconsistentConstructor },
	DiagnosticRuleReportOverlappingOverload:           func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportOverlappingOverload },
	DiagnosticRuleReportPossiblyUnboundVariable:       func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportPossiblyUnboundVariable },
	DiagnosticRuleReportMissingSuperCall:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMissingSuperCall },
	DiagnosticRuleReportUninitializedInstanceVariable: func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUninitializedInstanceVariable },
	DiagnosticRuleReportInvalidStringEscapeSequence:   func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInvalidStringEscapeSequence },
	DiagnosticRuleReportUnknownParameterType:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnknownParameterType },
	DiagnosticRuleReportUnknownArgumentType:           func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnknownArgumentType },
	DiagnosticRuleReportUnknownLambdaType:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnknownLambdaType },
	DiagnosticRuleReportUnknownVariableType:           func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnknownVariableType },
	DiagnosticRuleReportUnknownMemberType:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnknownMemberType },
	DiagnosticRuleReportMissingParameterType:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMissingParameterType },
	DiagnosticRuleReportMissingTypeArgument:           func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMissingTypeArgument },
	DiagnosticRuleReportInvalidTypeVarUse:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInvalidTypeVarUse },
	DiagnosticRuleReportCallInDefaultInitializer:      func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportCallInDefaultInitializer },
	DiagnosticRuleReportUnnecessaryIsInstance:         func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnnecessaryIsInstance },
	DiagnosticRuleReportUnnecessaryCast:               func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnnecessaryCast },
	DiagnosticRuleReportUnnecessaryComparison:         func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnnecessaryComparison },
	DiagnosticRuleReportUnnecessaryContains:           func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnnecessaryContains },
	DiagnosticRuleReportAssertAlwaysTrue:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportAssertAlwaysTrue },
	DiagnosticRuleReportSelfClsParameterName:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportSelfClsParameterName },
	DiagnosticRuleReportImplicitStringConcatenation:   func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportImplicitStringConcatenation },
	DiagnosticRuleReportUndefinedVariable:             func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUndefinedVariable },
	DiagnosticRuleReportUnboundVariable:               func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnboundVariable },
	DiagnosticRuleReportUnhashable:                    func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnhashable },
	DiagnosticRuleReportInvalidStubStatement:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportInvalidStubStatement },
	DiagnosticRuleReportIncompleteStub:                func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportIncompleteStub },
	DiagnosticRuleReportUnsupportedDunderAll:          func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnsupportedDunderAll },
	DiagnosticRuleReportUnusedCallResult:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedCallResult },
	DiagnosticRuleReportUnusedCoroutine:               func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedCoroutine },
	DiagnosticRuleReportUnusedExcept:                  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedExcept },
	DiagnosticRuleReportUnusedExpression:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnusedExpression },
	DiagnosticRuleReportUnnecessaryTypeIgnoreComment:  func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnnecessaryTypeIgnoreComment },
	DiagnosticRuleReportMatchNotExhaustive:            func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportMatchNotExhaustive },
	DiagnosticRuleReportUnreachable:                   func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportUnreachable },
	DiagnosticRuleReportImplicitOverride:              func(rs *DiagnosticRuleSet) *DiagnosticLevel { return &rs.ReportImplicitOverride },
}

// GetBooleanDiagnosticRules returns a list of the diagnostic rules that are
// configured with a true or false value. The TypeScript defaults
// includeNonOverridable to false.
func GetBooleanDiagnosticRules(includeNonOverridable bool) []DiagnosticRule {
	boolRules := []DiagnosticRule{
		DiagnosticRuleStrictListInference,
		DiagnosticRuleStrictSetInference,
		DiagnosticRuleStrictDictionaryInference,
		DiagnosticRuleAnalyzeUnannotatedFunctions,
		DiagnosticRuleStrictParameterNoneValue,
		DiagnosticRuleEnableExperimentalFeatures,
		DiagnosticRuleDeprecateTypingAliases,
		DiagnosticRuleDisableBytesTypePromotions,
	}

	if includeNonOverridable {
		// Do not include these because we don't want to override it in strict
		// mode or support it within pyright comments.
		boolRules = append(boolRules, DiagnosticRuleEnableTypeIgnoreComments)
		boolRules = append(boolRules, DiagnosticRuleEnableReachabilityAnalysis)
	}

	return boolRules
}

// GetDiagLevelDiagnosticRules returns a list of the diagnostic rules that are
// configured with a diagnostic level ('none', 'error', etc.).
func GetDiagLevelDiagnosticRules() []DiagnosticRule {
	return []DiagnosticRule{
		DiagnosticRuleReportGeneralTypeIssues,
		DiagnosticRuleReportPropertyTypeMismatch,
		DiagnosticRuleReportFunctionMemberAccess,
		DiagnosticRuleReportMissingImports,
		DiagnosticRuleReportMissingModuleSource,
		DiagnosticRuleReportInvalidTypeForm,
		DiagnosticRuleReportMissingTypeStubs,
		DiagnosticRuleReportImportCycles,
		DiagnosticRuleReportUnusedImport,
		DiagnosticRuleReportUnusedClass,
		DiagnosticRuleReportUnusedFunction,
		DiagnosticRuleReportUnusedVariable,
		DiagnosticRuleReportDuplicateImport,
		DiagnosticRuleReportWildcardImportFromLibrary,
		DiagnosticRuleReportAbstractUsage,
		DiagnosticRuleReportArgumentType,
		DiagnosticRuleReportAssertTypeFailure,
		DiagnosticRuleReportAssignmentType,
		DiagnosticRuleReportAttributeAccessIssue,
		DiagnosticRuleReportCallIssue,
		DiagnosticRuleReportInconsistentOverload,
		DiagnosticRuleReportIndexIssue,
		DiagnosticRuleReportInvalidTypeArguments,
		DiagnosticRuleReportNoOverloadImplementation,
		DiagnosticRuleReportOperatorIssue,
		DiagnosticRuleReportOptionalSubscript,
		DiagnosticRuleReportOptionalMemberAccess,
		DiagnosticRuleReportOptionalCall,
		DiagnosticRuleReportOptionalIterable,
		DiagnosticRuleReportOptionalContextManager,
		DiagnosticRuleReportOptionalOperand,
		DiagnosticRuleReportRedeclaration,
		DiagnosticRuleReportReturnType,
		DiagnosticRuleReportTypedDictNotRequiredAccess,
		DiagnosticRuleReportUntypedFunctionDecorator,
		DiagnosticRuleReportUntypedClassDecorator,
		DiagnosticRuleReportUntypedBaseClass,
		DiagnosticRuleReportUntypedNamedTuple,
		DiagnosticRuleReportPrivateUsage,
		DiagnosticRuleReportTypeCommentUsage,
		DiagnosticRuleReportPrivateImportUsage,
		DiagnosticRuleReportConstantRedefinition,
		DiagnosticRuleReportDeprecated,
		DiagnosticRuleReportIncompatibleMethodOverride,
		DiagnosticRuleReportIncompatibleVariableOverride,
		DiagnosticRuleReportInconsistentConstructor,
		DiagnosticRuleReportOverlappingOverload,
		DiagnosticRuleReportPossiblyUnboundVariable,
		DiagnosticRuleReportMissingSuperCall,
		DiagnosticRuleReportUninitializedInstanceVariable,
		DiagnosticRuleReportInvalidStringEscapeSequence,
		DiagnosticRuleReportUnknownParameterType,
		DiagnosticRuleReportUnknownArgumentType,
		DiagnosticRuleReportUnknownLambdaType,
		DiagnosticRuleReportUnknownVariableType,
		DiagnosticRuleReportUnknownMemberType,
		DiagnosticRuleReportMissingParameterType,
		DiagnosticRuleReportMissingTypeArgument,
		DiagnosticRuleReportInvalidTypeVarUse,
		DiagnosticRuleReportCallInDefaultInitializer,
		DiagnosticRuleReportUnnecessaryIsInstance,
		DiagnosticRuleReportUnnecessaryCast,
		DiagnosticRuleReportUnnecessaryComparison,
		DiagnosticRuleReportUnnecessaryContains,
		DiagnosticRuleReportAssertAlwaysTrue,
		DiagnosticRuleReportSelfClsParameterName,
		DiagnosticRuleReportImplicitStringConcatenation,
		DiagnosticRuleReportUndefinedVariable,
		DiagnosticRuleReportUnhashable,
		DiagnosticRuleReportUnboundVariable,
		DiagnosticRuleReportInvalidStubStatement,
		DiagnosticRuleReportIncompleteStub,
		DiagnosticRuleReportUnsupportedDunderAll,
		DiagnosticRuleReportUnusedCallResult,
		DiagnosticRuleReportUnusedCoroutine,
		DiagnosticRuleReportUnusedExcept,
		DiagnosticRuleReportUnusedExpression,
		DiagnosticRuleReportUnnecessaryTypeIgnoreComment,
		DiagnosticRuleReportMatchNotExhaustive,
		DiagnosticRuleReportUnreachable,
		DiagnosticRuleReportImplicitOverride,
	}
}

// GetStrictModeNotOverriddenRules corresponds to
// getStrictModeNotOverriddenRules. In strict mode, the value in the user
// config file should be honored and not overwritten by the value from the
// strict rule set.
func GetStrictModeNotOverriddenRules() []DiagnosticRule {
	return []DiagnosticRule{
		DiagnosticRuleReportMissingModuleSource,
	}
}

// GetOffDiagnosticRuleSet corresponds to getOffDiagnosticRuleSet.
func GetOffDiagnosticRuleSet() *DiagnosticRuleSet {
	return &DiagnosticRuleSet{
		PrintUnknownAsAny:                   true,
		OmitTypeArgsIfUnknown:               true,
		OmitUnannotatedParamType:            true,
		OmitConditionalConstraint:           true,
		Pep604Printing:                      true,
		StrictListInference:                 false,
		StrictSetInference:                  false,
		StrictDictionaryInference:           false,
		AnalyzeUnannotatedFunctions:         true,
		StrictParameterNoneValue:            true,
		EnableExperimentalFeatures:          false,
		EnableTypeIgnoreComments:            true,
		EnableReachabilityAnalysis:          false,
		DeprecateTypingAliases:              false,
		DisableBytesTypePromotions:          true,
		ReportGeneralTypeIssues:             "none",
		ReportPropertyTypeMismatch:          "none",
		ReportFunctionMemberAccess:          "none",
		ReportMissingImports:                "warning",
		ReportMissingModuleSource:           "warning",
		ReportInvalidTypeForm:               "warning",
		ReportMissingTypeStubs:              "none",
		ReportImportCycles:                  "none",
		ReportUnusedImport:                  "none",
		ReportUnusedClass:                   "none",
		ReportUnusedFunction:                "none",
		ReportUnusedVariable:                "none",
		ReportDuplicateImport:               "none",
		ReportWildcardImportFromLibrary:     "none",
		ReportAbstractUsage:                 "none",
		ReportArgumentType:                  "none",
		ReportAssertTypeFailure:             "none",
		ReportAssignmentType:                "none",
		ReportAttributeAccessIssue:          "none",
		ReportCallIssue:                     "none",
		ReportInconsistentOverload:          "none",
		ReportIndexIssue:                    "none",
		ReportInvalidTypeArguments:          "none",
		ReportNoOverloadImplementation:      "none",
		ReportOperatorIssue:                 "none",
		ReportOptionalSubscript:             "none",
		ReportOptionalMemberAccess:          "none",
		ReportOptionalCall:                  "none",
		ReportOptionalIterable:              "none",
		ReportOptionalContextManager:        "none",
		ReportOptionalOperand:               "none",
		ReportRedeclaration:                 "none",
		ReportReturnType:                    "none",
		ReportTypedDictNotRequiredAccess:    "none",
		ReportUntypedFunctionDecorator:      "none",
		ReportUntypedClassDecorator:         "none",
		ReportUntypedBaseClass:              "none",
		ReportUntypedNamedTuple:             "none",
		ReportPrivateUsage:                  "none",
		ReportTypeCommentUsage:              "none",
		ReportPrivateImportUsage:            "none",
		ReportConstantRedefinition:          "none",
		ReportDeprecated:                    "none",
		ReportIncompatibleMethodOverride:    "none",
		ReportIncompatibleVariableOverride:  "none",
		ReportInconsistentConstructor:       "none",
		ReportOverlappingOverload:           "none",
		ReportPossiblyUnboundVariable:       "none",
		ReportMissingSuperCall:              "none",
		ReportUninitializedInstanceVariable: "none",
		ReportInvalidStringEscapeSequence:   "none",
		ReportUnknownParameterType:          "none",
		ReportUnknownArgumentType:           "none",
		ReportUnknownLambdaType:             "none",
		ReportUnknownVariableType:           "none",
		ReportUnknownMemberType:             "none",
		ReportMissingParameterType:          "none",
		ReportMissingTypeArgument:           "none",
		ReportInvalidTypeVarUse:             "none",
		ReportCallInDefaultInitializer:      "none",
		ReportUnnecessaryIsInstance:         "none",
		ReportUnnecessaryCast:               "none",
		ReportUnnecessaryComparison:         "none",
		ReportUnnecessaryContains:           "none",
		ReportAssertAlwaysTrue:              "none",
		ReportSelfClsParameterName:          "none",
		ReportImplicitStringConcatenation:   "none",
		ReportUndefinedVariable:             "warning",
		ReportUnboundVariable:               "none",
		ReportUnhashable:                    "none",
		ReportInvalidStubStatement:          "none",
		ReportIncompleteStub:                "none",
		ReportUnsupportedDunderAll:          "none",
		ReportUnusedCallResult:              "none",
		ReportUnusedCoroutine:               "none",
		ReportUnusedExcept:                  "none",
		ReportUnusedExpression:              "none",
		ReportUnnecessaryTypeIgnoreComment:  "none",
		ReportMatchNotExhaustive:            "none",
		ReportUnreachable:                   "none",
		ReportImplicitOverride:              "none",
	}
}

// GetBasicDiagnosticRuleSet corresponds to getBasicDiagnosticRuleSet.
func GetBasicDiagnosticRuleSet() *DiagnosticRuleSet {
	return &DiagnosticRuleSet{
		PrintUnknownAsAny:                   false,
		OmitTypeArgsIfUnknown:               false,
		OmitUnannotatedParamType:            true,
		OmitConditionalConstraint:           false,
		Pep604Printing:                      true,
		StrictListInference:                 false,
		StrictSetInference:                  false,
		StrictDictionaryInference:           false,
		AnalyzeUnannotatedFunctions:         true,
		StrictParameterNoneValue:            true,
		EnableExperimentalFeatures:          false,
		EnableTypeIgnoreComments:            true,
		EnableReachabilityAnalysis:          true,
		DeprecateTypingAliases:              false,
		DisableBytesTypePromotions:          true,
		ReportGeneralTypeIssues:             "error",
		ReportPropertyTypeMismatch:          "none",
		ReportFunctionMemberAccess:          "none",
		ReportMissingImports:                "error",
		ReportMissingModuleSource:           "warning",
		ReportInvalidTypeForm:               "error",
		ReportMissingTypeStubs:              "none",
		ReportImportCycles:                  "none",
		ReportUnusedImport:                  "none",
		ReportUnusedClass:                   "none",
		ReportUnusedFunction:                "none",
		ReportUnusedVariable:                "none",
		ReportDuplicateImport:               "none",
		ReportWildcardImportFromLibrary:     "warning",
		ReportAbstractUsage:                 "error",
		ReportArgumentType:                  "error",
		ReportAssertTypeFailure:             "error",
		ReportAssignmentType:                "error",
		ReportAttributeAccessIssue:          "error",
		ReportCallIssue:                     "error",
		ReportInconsistentOverload:          "error",
		ReportIndexIssue:                    "error",
		ReportInvalidTypeArguments:          "error",
		ReportNoOverloadImplementation:      "error",
		ReportOperatorIssue:                 "error",
		ReportOptionalSubscript:             "error",
		ReportOptionalMemberAccess:          "error",
		ReportOptionalCall:                  "error",
		ReportOptionalIterable:              "error",
		ReportOptionalContextManager:        "error",
		ReportOptionalOperand:               "error",
		ReportRedeclaration:                 "error",
		ReportReturnType:                    "error",
		ReportTypedDictNotRequiredAccess:    "error",
		ReportUntypedFunctionDecorator:      "none",
		ReportUntypedClassDecorator:         "none",
		ReportUntypedBaseClass:              "none",
		ReportUntypedNamedTuple:             "none",
		ReportPrivateUsage:                  "none",
		ReportTypeCommentUsage:              "none",
		ReportPrivateImportUsage:            "error",
		ReportConstantRedefinition:          "none",
		ReportDeprecated:                    "none",
		ReportIncompatibleMethodOverride:    "none",
		ReportIncompatibleVariableOverride:  "none",
		ReportInconsistentConstructor:       "none",
		ReportOverlappingOverload:           "none",
		ReportPossiblyUnboundVariable:       "none",
		ReportMissingSuperCall:              "none",
		ReportUninitializedInstanceVariable: "none",
		ReportInvalidStringEscapeSequence:   "warning",
		ReportUnknownParameterType:          "none",
		ReportUnknownArgumentType:           "none",
		ReportUnknownLambdaType:             "none",
		ReportUnknownVariableType:           "none",
		ReportUnknownMemberType:             "none",
		ReportMissingParameterType:          "none",
		ReportMissingTypeArgument:           "none",
		ReportInvalidTypeVarUse:             "warning",
		ReportCallInDefaultInitializer:      "none",
		ReportUnnecessaryIsInstance:         "none",
		ReportUnnecessaryCast:               "none",
		ReportUnnecessaryComparison:         "none",
		ReportUnnecessaryContains:           "none",
		ReportAssertAlwaysTrue:              "warning",
		ReportSelfClsParameterName:          "warning",
		ReportImplicitStringConcatenation:   "none",
		ReportUndefinedVariable:             "error",
		ReportUnboundVariable:               "error",
		ReportUnhashable:                    "error",
		ReportInvalidStubStatement:          "none",
		ReportIncompleteStub:                "none",
		ReportUnsupportedDunderAll:          "warning",
		ReportUnusedCallResult:              "none",
		ReportUnusedCoroutine:               "error",
		ReportUnusedExcept:                  "error",
		ReportUnusedExpression:              "warning",
		ReportUnnecessaryTypeIgnoreComment:  "none",
		ReportMatchNotExhaustive:            "none",
		ReportUnreachable:                   "none",
		ReportImplicitOverride:              "none",
	}
}

// GetStandardDiagnosticRuleSet corresponds to getStandardDiagnosticRuleSet.
func GetStandardDiagnosticRuleSet() *DiagnosticRuleSet {
	return &DiagnosticRuleSet{
		PrintUnknownAsAny:                   false,
		OmitTypeArgsIfUnknown:               false,
		OmitUnannotatedParamType:            true,
		OmitConditionalConstraint:           false,
		Pep604Printing:                      true,
		StrictListInference:                 false,
		StrictSetInference:                  false,
		StrictDictionaryInference:           false,
		AnalyzeUnannotatedFunctions:         true,
		StrictParameterNoneValue:            true,
		EnableExperimentalFeatures:          false,
		EnableTypeIgnoreComments:            true,
		EnableReachabilityAnalysis:          true,
		DeprecateTypingAliases:              false,
		DisableBytesTypePromotions:          true,
		ReportGeneralTypeIssues:             "error",
		ReportPropertyTypeMismatch:          "none",
		ReportFunctionMemberAccess:          "error",
		ReportMissingImports:                "error",
		ReportMissingModuleSource:           "warning",
		ReportInvalidTypeForm:               "error",
		ReportMissingTypeStubs:              "none",
		ReportImportCycles:                  "none",
		ReportUnusedImport:                  "none",
		ReportUnusedClass:                   "none",
		ReportUnusedFunction:                "none",
		ReportUnusedVariable:                "none",
		ReportDuplicateImport:               "none",
		ReportWildcardImportFromLibrary:     "warning",
		ReportAbstractUsage:                 "error",
		ReportArgumentType:                  "error",
		ReportAssertTypeFailure:             "error",
		ReportAssignmentType:                "error",
		ReportAttributeAccessIssue:          "error",
		ReportCallIssue:                     "error",
		ReportInconsistentOverload:          "error",
		ReportIndexIssue:                    "error",
		ReportInvalidTypeArguments:          "error",
		ReportNoOverloadImplementation:      "error",
		ReportOperatorIssue:                 "error",
		ReportOptionalSubscript:             "error",
		ReportOptionalMemberAccess:          "error",
		ReportOptionalCall:                  "error",
		ReportOptionalIterable:              "error",
		ReportOptionalContextManager:        "error",
		ReportOptionalOperand:               "error",
		ReportRedeclaration:                 "error",
		ReportReturnType:                    "error",
		ReportTypedDictNotRequiredAccess:    "error",
		ReportUntypedFunctionDecorator:      "none",
		ReportUntypedClassDecorator:         "none",
		ReportUntypedBaseClass:              "none",
		ReportUntypedNamedTuple:             "none",
		ReportPrivateUsage:                  "none",
		ReportTypeCommentUsage:              "none",
		ReportPrivateImportUsage:            "error",
		ReportConstantRedefinition:          "none",
		ReportDeprecated:                    "none",
		ReportIncompatibleMethodOverride:    "error",
		ReportIncompatibleVariableOverride:  "error",
		ReportInconsistentConstructor:       "none",
		ReportOverlappingOverload:           "error",
		ReportPossiblyUnboundVariable:       "error",
		ReportMissingSuperCall:              "none",
		ReportUninitializedInstanceVariable: "none",
		ReportInvalidStringEscapeSequence:   "warning",
		ReportUnknownParameterType:          "none",
		ReportUnknownArgumentType:           "none",
		ReportUnknownLambdaType:             "none",
		ReportUnknownVariableType:           "none",
		ReportUnknownMemberType:             "none",
		ReportMissingParameterType:          "none",
		ReportMissingTypeArgument:           "none",
		ReportInvalidTypeVarUse:             "warning",
		ReportCallInDefaultInitializer:      "none",
		ReportUnnecessaryIsInstance:         "none",
		ReportUnnecessaryCast:               "none",
		ReportUnnecessaryComparison:         "none",
		ReportUnnecessaryContains:           "none",
		ReportAssertAlwaysTrue:              "warning",
		ReportSelfClsParameterName:          "warning",
		ReportImplicitStringConcatenation:   "none",
		ReportUndefinedVariable:             "error",
		ReportUnboundVariable:               "error",
		ReportUnhashable:                    "error",
		ReportInvalidStubStatement:          "none",
		ReportIncompleteStub:                "none",
		ReportUnsupportedDunderAll:          "warning",
		ReportUnusedCallResult:              "none",
		ReportUnusedCoroutine:               "error",
		ReportUnusedExcept:                  "error",
		ReportUnusedExpression:              "warning",
		ReportUnnecessaryTypeIgnoreComment:  "none",
		ReportMatchNotExhaustive:            "none",
		ReportUnreachable:                   "none",
		ReportImplicitOverride:              "none",
	}
}

// GetStrictDiagnosticRuleSet corresponds to getStrictDiagnosticRuleSet.
func GetStrictDiagnosticRuleSet() *DiagnosticRuleSet {
	return &DiagnosticRuleSet{
		PrintUnknownAsAny:                   false,
		OmitTypeArgsIfUnknown:               false,
		OmitUnannotatedParamType:            false,
		OmitConditionalConstraint:           false,
		Pep604Printing:                      true,
		StrictListInference:                 true,
		StrictSetInference:                  true,
		StrictDictionaryInference:           true,
		AnalyzeUnannotatedFunctions:         true,
		StrictParameterNoneValue:            true,
		EnableExperimentalFeatures:          false,
		EnableTypeIgnoreComments:            true,
		EnableReachabilityAnalysis:          true,
		DeprecateTypingAliases:              false,
		DisableBytesTypePromotions:          true,
		ReportGeneralTypeIssues:             "error",
		ReportPropertyTypeMismatch:          "none",
		ReportFunctionMemberAccess:          "error",
		ReportMissingImports:                "error",
		ReportMissingModuleSource:           "warning",
		ReportInvalidTypeForm:               "error",
		ReportMissingTypeStubs:              "error",
		ReportImportCycles:                  "none",
		ReportUnusedImport:                  "error",
		ReportUnusedClass:                   "error",
		ReportUnusedFunction:                "error",
		ReportUnusedVariable:                "error",
		ReportDuplicateImport:               "error",
		ReportWildcardImportFromLibrary:     "error",
		ReportAbstractUsage:                 "error",
		ReportArgumentType:                  "error",
		ReportAssertTypeFailure:             "error",
		ReportAssignmentType:                "error",
		ReportAttributeAccessIssue:          "error",
		ReportCallIssue:                     "error",
		ReportInconsistentOverload:          "error",
		ReportIndexIssue:                    "error",
		ReportInvalidTypeArguments:          "error",
		ReportNoOverloadImplementation:      "error",
		ReportOperatorIssue:                 "error",
		ReportOptionalSubscript:             "error",
		ReportOptionalMemberAccess:          "error",
		ReportOptionalCall:                  "error",
		ReportOptionalIterable:              "error",
		ReportOptionalContextManager:        "error",
		ReportOptionalOperand:               "error",
		ReportRedeclaration:                 "error",
		ReportReturnType:                    "error",
		ReportTypedDictNotRequiredAccess:    "error",
		ReportUntypedFunctionDecorator:      "error",
		ReportUntypedClassDecorator:         "error",
		ReportUntypedBaseClass:              "error",
		ReportUntypedNamedTuple:             "error",
		ReportPrivateUsage:                  "error",
		ReportTypeCommentUsage:              "error",
		ReportPrivateImportUsage:            "error",
		ReportConstantRedefinition:          "error",
		ReportDeprecated:                    "error",
		ReportIncompatibleMethodOverride:    "error",
		ReportIncompatibleVariableOverride:  "error",
		ReportInconsistentConstructor:       "error",
		ReportOverlappingOverload:           "error",
		ReportPossiblyUnboundVariable:       "error",
		ReportMissingSuperCall:              "none",
		ReportUninitializedInstanceVariable: "none",
		ReportInvalidStringEscapeSequence:   "error",
		ReportUnknownParameterType:          "error",
		ReportUnknownArgumentType:           "error",
		ReportUnknownLambdaType:             "error",
		ReportUnknownVariableType:           "error",
		ReportUnknownMemberType:             "error",
		ReportMissingParameterType:          "error",
		ReportMissingTypeArgument:           "error",
		ReportInvalidTypeVarUse:             "error",
		ReportCallInDefaultInitializer:      "none",
		ReportUnnecessaryIsInstance:         "error",
		ReportUnnecessaryCast:               "error",
		ReportUnnecessaryComparison:         "error",
		ReportUnnecessaryContains:           "error",
		ReportAssertAlwaysTrue:              "error",
		ReportSelfClsParameterName:          "error",
		ReportImplicitStringConcatenation:   "none",
		ReportUndefinedVariable:             "error",
		ReportUnboundVariable:               "error",
		ReportUnhashable:                    "error",
		ReportInvalidStubStatement:          "error",
		ReportIncompleteStub:                "error",
		ReportUnsupportedDunderAll:          "error",
		ReportUnusedCallResult:              "none",
		ReportUnusedCoroutine:               "error",
		ReportUnusedExcept:                  "error",
		ReportUnusedExpression:              "error",
		ReportUnnecessaryTypeIgnoreComment:  "none",
		ReportMatchNotExhaustive:            "error",
		ReportUnreachable:                   "none",
		ReportImplicitOverride:              "none",
	}
}
