/*
 * parsetreewalker.go
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT license.
 * Author: Eric Traut
 *
 * Traverses a parse tree.
 *
 * GENERATED by analyzer/gen/generate_parsetreewalker.py from
 * analyzer/parseTreeWalker.ts (pyright 1.1.412). Do not edit by hand; the
 * two big switches cover all 78 parse node types and generating them means a
 * case cannot be silently dropped.
 *
 * The TypeScript returns `(ParseNode | undefined)[]` from getChildNodes and
 * filters the undefined entries in walkMultiple. Nil entries are kept here for
 * the same reason and filtered in the same place.
 */

package analyzer

import (
	"github.com/microsoft/pyright/go/common"
	"github.com/microsoft/pyright/go/parser"
)

// childOrNil normalizes an absent child to a nil interface value.
//
// A nil *XNode stored in a parser.ParseNode is a non-nil interface holding a
// nil pointer, so `child != nil` would be true for a child the original sees as
// `undefined`. Every caller of GetChildNodes filters with a truthiness test, so
// the normalization has to happen here.
func childOrNil[T parser.ParseNode](node T) parser.ParseNode {
	var zero T
	if any(node) == any(zero) {
		return nil
	}
	return node
}

// GetChildNodes returns the child nodes of the given node. Entries may be nil,
// matching the original's `(ParseNode | undefined)[]`.
func GetChildNodes(node parser.ParseNode) []parser.ParseNode {
	switch node.GetNodeType() {
	case parser.ParseNodeTypeError:
		n := node.(*parser.ErrorNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.Child))
		for _, c := range n.D.Decorators {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeArgument:
		n := node.(*parser.ArgumentNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.ValueExpr)}

	case parser.ParseNodeTypeAssert:
		n := node.(*parser.AssertNode)
		return []parser.ParseNode{childOrNil(n.D.TestExpr), childOrNil(n.D.ExceptionExpr)}

	case parser.ParseNodeTypeAssignmentExpression:
		n := node.(*parser.AssignmentExpressionNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.RightExpr)}

	case parser.ParseNodeTypeAssignment:
		n := node.(*parser.AssignmentNode)
		return []parser.ParseNode{childOrNil(n.D.LeftExpr), childOrNil(n.D.RightExpr), childOrNil(n.D.AnnotationComment)}

	case parser.ParseNodeTypeAugmentedAssignment:
		n := node.(*parser.AugmentedAssignmentNode)
		return []parser.ParseNode{childOrNil(n.D.LeftExpr), childOrNil(n.D.RightExpr)}

	case parser.ParseNodeTypeAwait:
		n := node.(*parser.AwaitNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeBinaryOperation:
		n := node.(*parser.BinaryOperationNode)
		return []parser.ParseNode{childOrNil(n.D.LeftExpr), childOrNil(n.D.RightExpr)}

	case parser.ParseNodeTypeBreak:
		return nil

	case parser.ParseNodeTypeCall:
		n := node.(*parser.CallNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.LeftExpr))
		for _, c := range n.D.Args {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeCase:
		n := node.(*parser.CaseNode)
		return []parser.ParseNode{childOrNil(n.D.Pattern), childOrNil(n.D.GuardExpr), childOrNil(n.D.Suite)}

	case parser.ParseNodeTypeClass:
		n := node.(*parser.ClassNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Decorators {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.Name))
		out = append(out, childOrNil(n.D.TypeParams))
		for _, c := range n.D.Arguments {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.Suite))
		return out

	case parser.ParseNodeTypeComprehension:
		n := node.(*parser.ComprehensionNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.Expr))
		for _, c := range n.D.ForIfNodes {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeComprehensionFor:
		n := node.(*parser.ComprehensionForNode)
		return []parser.ParseNode{childOrNil(n.D.TargetExpr), childOrNil(n.D.IterableExpr)}

	case parser.ParseNodeTypeComprehensionIf:
		n := node.(*parser.ComprehensionIfNode)
		return []parser.ParseNode{childOrNil(n.D.TestExpr)}

	case parser.ParseNodeTypeConstant:
		return nil

	case parser.ParseNodeTypeContinue:
		return nil

	case parser.ParseNodeTypeDecorator:
		n := node.(*parser.DecoratorNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeDel:
		n := node.(*parser.DelNode)
		out := make([]parser.ParseNode, 0, len(n.D.Targets))
		for _, c := range n.D.Targets {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeDictionary:
		n := node.(*parser.DictionaryNode)
		out := make([]parser.ParseNode, 0, len(n.D.Items))
		for _, c := range n.D.Items {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeDictionaryExpandEntry:
		n := node.(*parser.DictionaryExpandEntryNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeDictionaryKeyEntry:
		n := node.(*parser.DictionaryKeyEntryNode)
		return []parser.ParseNode{childOrNil(n.D.KeyExpr), childOrNil(n.D.ValueExpr)}

	case parser.ParseNodeTypeEllipsis:
		return nil

	case parser.ParseNodeTypeIf:
		n := node.(*parser.IfNode)
		return []parser.ParseNode{childOrNil(n.D.TestExpr), childOrNil(n.D.IfSuite), childOrNil(n.D.ElseSuite)}

	case parser.ParseNodeTypeImport:
		n := node.(*parser.ImportNode)
		out := make([]parser.ParseNode, 0, len(n.D.List))
		for _, c := range n.D.List {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeImportAs:
		n := node.(*parser.ImportAsNode)
		return []parser.ParseNode{childOrNil(n.D.Module), childOrNil(n.D.Alias)}

	case parser.ParseNodeTypeImportFrom:
		n := node.(*parser.ImportFromNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.Module))
		for _, c := range n.D.Imports {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeImportFromAs:
		n := node.(*parser.ImportFromAsNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.Alias)}

	case parser.ParseNodeTypeIndex:
		n := node.(*parser.IndexNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.LeftExpr))
		for _, c := range n.D.Items {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeExcept:
		n := node.(*parser.ExceptNode)
		return []parser.ParseNode{childOrNil(n.D.TypeExpr), childOrNil(n.D.Name), childOrNil(n.D.ExceptSuite)}

	case parser.ParseNodeTypeFor:
		n := node.(*parser.ForNode)
		return []parser.ParseNode{childOrNil(n.D.TargetExpr), childOrNil(n.D.IterableExpr), childOrNil(n.D.ForSuite), childOrNil(n.D.ElseSuite)}

	case parser.ParseNodeTypeFormatString:
		n := node.(*parser.FormatStringNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.FieldExprs {
			out = append(out, c)
		}
		for _, c := range n.D.FormatExprs {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeFunction:
		n := node.(*parser.FunctionNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Decorators {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.Name))
		out = append(out, childOrNil(n.D.TypeParams))
		for _, c := range n.D.Params {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.ReturnAnnotation))
		out = append(out, childOrNil(n.D.FuncAnnotationComment))
		out = append(out, childOrNil(n.D.Suite))
		return out

	case parser.ParseNodeTypeFunctionAnnotation:
		n := node.(*parser.FunctionAnnotationNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.ParamAnnotations {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.ReturnAnnotation))
		return out

	case parser.ParseNodeTypeGlobal:
		n := node.(*parser.GlobalNode)
		out := make([]parser.ParseNode, 0, len(n.D.Targets))
		for _, c := range n.D.Targets {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeLambda:
		n := node.(*parser.LambdaNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Params {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.Expr))
		return out

	case parser.ParseNodeTypeList:
		n := node.(*parser.ListNode)
		out := make([]parser.ParseNode, 0, len(n.D.Items))
		for _, c := range n.D.Items {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeMatch:
		n := node.(*parser.MatchNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.Expr))
		for _, c := range n.D.Cases {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeMemberAccess:
		n := node.(*parser.MemberAccessNode)
		return []parser.ParseNode{childOrNil(n.D.LeftExpr), childOrNil(n.D.Member)}

	case parser.ParseNodeTypeModuleName:
		n := node.(*parser.ModuleNameNode)
		out := make([]parser.ParseNode, 0, len(n.D.NameParts))
		for _, c := range n.D.NameParts {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeModule:
		n := node.(*parser.ModuleNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Statements {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeName:
		return nil

	case parser.ParseNodeTypeNonlocal:
		n := node.(*parser.NonlocalNode)
		out := make([]parser.ParseNode, 0, len(n.D.Targets))
		for _, c := range n.D.Targets {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeNumber:
		return nil

	case parser.ParseNodeTypeParameter:
		n := node.(*parser.ParameterNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.Annotation), childOrNil(n.D.AnnotationComment), childOrNil(n.D.DefaultValue)}

	case parser.ParseNodeTypePass:
		return nil

	case parser.ParseNodeTypePatternAs:
		n := node.(*parser.PatternAsNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.OrPatterns {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.Target))
		return out

	case parser.ParseNodeTypePatternClass:
		n := node.(*parser.PatternClassNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.ClassName))
		for _, c := range n.D.Args {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypePatternClassArgument:
		n := node.(*parser.PatternClassArgumentNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.Pattern)}

	case parser.ParseNodeTypePatternCapture:
		n := node.(*parser.PatternCaptureNode)
		return []parser.ParseNode{childOrNil(n.D.Target)}

	case parser.ParseNodeTypePatternLiteral:
		n := node.(*parser.PatternLiteralNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypePatternMappingExpandEntry:
		n := node.(*parser.PatternMappingExpandEntryNode)
		return []parser.ParseNode{childOrNil(n.D.Target)}

	case parser.ParseNodeTypePatternMappingKeyEntry:
		n := node.(*parser.PatternMappingKeyEntryNode)
		return []parser.ParseNode{childOrNil(n.D.KeyPattern), childOrNil(n.D.ValuePattern)}

	case parser.ParseNodeTypePatternMapping:
		n := node.(*parser.PatternMappingNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Entries {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypePatternSequence:
		n := node.(*parser.PatternSequenceNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Entries {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypePatternValue:
		n := node.(*parser.PatternValueNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeRaise:
		n := node.(*parser.RaiseNode)
		return []parser.ParseNode{childOrNil(n.D.Expr), childOrNil(n.D.FromExpr)}

	case parser.ParseNodeTypeReturn:
		n := node.(*parser.ReturnNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeSet:
		n := node.(*parser.SetNode)
		out := make([]parser.ParseNode, 0, len(n.D.Items))
		for _, c := range n.D.Items {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeSlice:
		n := node.(*parser.SliceNode)
		return []parser.ParseNode{childOrNil(n.D.StartValue), childOrNil(n.D.EndValue), childOrNil(n.D.StepValue)}

	case parser.ParseNodeTypeStatementList:
		n := node.(*parser.StatementListNode)
		out := make([]parser.ParseNode, 0, len(n.D.Statements))
		for _, c := range n.D.Statements {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeStringList:
		n := node.(*parser.StringListNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.Annotation))
		for _, c := range n.D.Strings {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeString:
		return nil

	case parser.ParseNodeTypeSuite:
		n := node.(*parser.SuiteNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Statements {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeTernary:
		n := node.(*parser.TernaryNode)
		return []parser.ParseNode{childOrNil(n.D.IfExpr), childOrNil(n.D.TestExpr), childOrNil(n.D.ElseExpr)}

	case parser.ParseNodeTypeTuple:
		n := node.(*parser.TupleNode)
		out := make([]parser.ParseNode, 0, len(n.D.Items))
		for _, c := range n.D.Items {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeTry:
		n := node.(*parser.TryNode)
		out := []parser.ParseNode{}
		out = append(out, childOrNil(n.D.TrySuite))
		for _, c := range n.D.ExceptClauses {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.ElseSuite))
		out = append(out, childOrNil(n.D.FinallySuite))
		return out

	case parser.ParseNodeTypeTypeAlias:
		n := node.(*parser.TypeAliasNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.TypeParams), childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeTypeAnnotation:
		n := node.(*parser.TypeAnnotationNode)
		return []parser.ParseNode{childOrNil(n.D.ValueExpr), childOrNil(n.D.Annotation)}

	case parser.ParseNodeTypeTypeParameter:
		n := node.(*parser.TypeParameterNode)
		return []parser.ParseNode{childOrNil(n.D.Name), childOrNil(n.D.BoundExpr), childOrNil(n.D.DefaultExpr)}

	case parser.ParseNodeTypeTypeParameterList:
		n := node.(*parser.TypeParameterListNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.Params {
			out = append(out, c)
		}
		return out

	case parser.ParseNodeTypeUnaryOperation:
		n := node.(*parser.UnaryOperationNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeUnpack:
		n := node.(*parser.UnpackNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeWhile:
		n := node.(*parser.WhileNode)
		return []parser.ParseNode{childOrNil(n.D.TestExpr), childOrNil(n.D.WhileSuite), childOrNil(n.D.ElseSuite)}

	case parser.ParseNodeTypeWith:
		n := node.(*parser.WithNode)
		out := []parser.ParseNode{}
		for _, c := range n.D.WithItems {
			out = append(out, c)
		}
		out = append(out, childOrNil(n.D.Suite))
		return out

	case parser.ParseNodeTypeWithItem:
		n := node.(*parser.WithItemNode)
		return []parser.ParseNode{childOrNil(n.D.Expr), childOrNil(n.D.Target)}

	case parser.ParseNodeTypeYield:
		n := node.(*parser.YieldNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	case parser.ParseNodeTypeYieldFrom:
		n := node.(*parser.YieldFromNode)
		return []parser.ParseNode{childOrNil(n.D.Expr)}

	}

	return nil
}

// ParseTreeVisitorOverrides is the set of methods a ParseTreeWalker subclass
// may override, one per parse node type. *ParseTreeWalker implements all of
// them by returning the walker's default value.
//
// A visit method returning true means "walk my children"; returning false means
// the handler has already dealt with them.
//
// Walk is part of the interface because the original's subclasses override it
// -- checker.ts wraps it to suppress diagnostics under unreachable code -- and
// the recursion in WalkMultiple has to reach the override rather than the
// embedded default.
type ParseTreeVisitorOverrides interface {
	Walk(node parser.ParseNode)
	VisitError(node *parser.ErrorNode) bool
	VisitArgument(node *parser.ArgumentNode) bool
	VisitAssert(node *parser.AssertNode) bool
	VisitAssignmentExpression(node *parser.AssignmentExpressionNode) bool
	VisitAssignment(node *parser.AssignmentNode) bool
	VisitAugmentedAssignment(node *parser.AugmentedAssignmentNode) bool
	VisitAwait(node *parser.AwaitNode) bool
	VisitBinaryOperation(node *parser.BinaryOperationNode) bool
	VisitBreak(node *parser.BreakNode) bool
	VisitCall(node *parser.CallNode) bool
	VisitCase(node *parser.CaseNode) bool
	VisitClass(node *parser.ClassNode) bool
	VisitComprehension(node *parser.ComprehensionNode) bool
	VisitComprehensionFor(node *parser.ComprehensionForNode) bool
	VisitComprehensionIf(node *parser.ComprehensionIfNode) bool
	VisitConstant(node *parser.ConstantNode) bool
	VisitContinue(node *parser.ContinueNode) bool
	VisitDecorator(node *parser.DecoratorNode) bool
	VisitDel(node *parser.DelNode) bool
	VisitDictionary(node *parser.DictionaryNode) bool
	VisitDictionaryExpandEntry(node *parser.DictionaryExpandEntryNode) bool
	VisitDictionaryKeyEntry(node *parser.DictionaryKeyEntryNode) bool
	VisitEllipsis(node *parser.EllipsisNode) bool
	VisitIf(node *parser.IfNode) bool
	VisitImport(node *parser.ImportNode) bool
	VisitImportAs(node *parser.ImportAsNode) bool
	VisitImportFrom(node *parser.ImportFromNode) bool
	VisitImportFromAs(node *parser.ImportFromAsNode) bool
	VisitIndex(node *parser.IndexNode) bool
	VisitExcept(node *parser.ExceptNode) bool
	VisitFor(node *parser.ForNode) bool
	VisitFormatString(node *parser.FormatStringNode) bool
	VisitFunction(node *parser.FunctionNode) bool
	VisitFunctionAnnotation(node *parser.FunctionAnnotationNode) bool
	VisitGlobal(node *parser.GlobalNode) bool
	VisitLambda(node *parser.LambdaNode) bool
	VisitList(node *parser.ListNode) bool
	VisitMatch(node *parser.MatchNode) bool
	VisitMemberAccess(node *parser.MemberAccessNode) bool
	VisitModuleName(node *parser.ModuleNameNode) bool
	VisitModule(node *parser.ModuleNode) bool
	VisitName(node *parser.NameNode) bool
	VisitNonlocal(node *parser.NonlocalNode) bool
	VisitNumber(node *parser.NumberNode) bool
	VisitParameter(node *parser.ParameterNode) bool
	VisitPass(node *parser.PassNode) bool
	VisitPatternAs(node *parser.PatternAsNode) bool
	VisitPatternClass(node *parser.PatternClassNode) bool
	VisitPatternClassArgument(node *parser.PatternClassArgumentNode) bool
	VisitPatternCapture(node *parser.PatternCaptureNode) bool
	VisitPatternLiteral(node *parser.PatternLiteralNode) bool
	VisitPatternMappingExpandEntry(node *parser.PatternMappingExpandEntryNode) bool
	VisitPatternMappingKeyEntry(node *parser.PatternMappingKeyEntryNode) bool
	VisitPatternMapping(node *parser.PatternMappingNode) bool
	VisitPatternSequence(node *parser.PatternSequenceNode) bool
	VisitPatternValue(node *parser.PatternValueNode) bool
	VisitRaise(node *parser.RaiseNode) bool
	VisitReturn(node *parser.ReturnNode) bool
	VisitSet(node *parser.SetNode) bool
	VisitSlice(node *parser.SliceNode) bool
	VisitStatementList(node *parser.StatementListNode) bool
	VisitStringList(node *parser.StringListNode) bool
	VisitString(node *parser.StringNode) bool
	VisitSuite(node *parser.SuiteNode) bool
	VisitTernary(node *parser.TernaryNode) bool
	VisitTuple(node *parser.TupleNode) bool
	VisitTry(node *parser.TryNode) bool
	VisitTypeAlias(node *parser.TypeAliasNode) bool
	VisitTypeAnnotation(node *parser.TypeAnnotationNode) bool
	VisitTypeParameter(node *parser.TypeParameterNode) bool
	VisitTypeParameterList(node *parser.TypeParameterListNode) bool
	VisitUnaryOperation(node *parser.UnaryOperationNode) bool
	VisitUnpack(node *parser.UnpackNode) bool
	VisitWhile(node *parser.WhileNode) bool
	VisitWith(node *parser.WithNode) bool
	VisitWithItem(node *parser.WithItemNode) bool
	VisitYield(node *parser.YieldNode) bool
	VisitYieldFrom(node *parser.YieldFromNode) bool
}

// ParseTreeWalker corresponds to the class of the same name, which extends
// ParseTreeVisitor<boolean> with a default of true.
type ParseTreeWalker struct {
	self         ParseTreeVisitorOverrides
	defaultValue bool
}

// NewParseTreeWalker returns a walker that dispatches to self. Pass the
// outermost embedder, not the embedded *ParseTreeWalker.
func NewParseTreeWalker(self ParseTreeVisitorOverrides) *ParseTreeWalker {
	return &ParseTreeWalker{self: self, defaultValue: true}
}

// Walk corresponds to ParseTreeWalker.walk.
func (w *ParseTreeWalker) Walk(node parser.ParseNode) {
	childrenToWalk := w.VisitNode(node)
	if len(childrenToWalk) > 0 {
		w.WalkMultiple(childrenToWalk)
	}
}

// WalkMultiple corresponds to ParseTreeWalker.walkMultiple. It skips nil
// entries, which is where the original's `(ParseNode | undefined)[]` is
// filtered.
func (w *ParseTreeWalker) WalkMultiple(nodes []parser.ParseNode) {
	for _, node := range nodes {
		if node != nil {
			w.self.Walk(node)
		}
	}
}

// VisitNode corresponds to ParseTreeWalker.visitNode.
//
// The original notes: if this.visit(node) returns true, all child nodes for the
// node are returned. If the method returns false, we assume that the handler has
// already handled the child nodes, so an empty list is returned.
func (w *ParseTreeWalker) VisitNode(node parser.ParseNode) []parser.ParseNode {
	if w.Visit(node) {
		return GetChildNodes(node)
	}
	return nil
}

// Visit dispatches to the per-node-type visit method.
func (w *ParseTreeWalker) Visit(node parser.ParseNode) bool {
	switch node.GetNodeType() {
	case parser.ParseNodeTypeError:
		return w.self.VisitError(node.(*parser.ErrorNode))

	case parser.ParseNodeTypeArgument:
		return w.self.VisitArgument(node.(*parser.ArgumentNode))

	case parser.ParseNodeTypeAssert:
		return w.self.VisitAssert(node.(*parser.AssertNode))

	case parser.ParseNodeTypeAssignmentExpression:
		return w.self.VisitAssignmentExpression(node.(*parser.AssignmentExpressionNode))

	case parser.ParseNodeTypeAssignment:
		return w.self.VisitAssignment(node.(*parser.AssignmentNode))

	case parser.ParseNodeTypeAugmentedAssignment:
		return w.self.VisitAugmentedAssignment(node.(*parser.AugmentedAssignmentNode))

	case parser.ParseNodeTypeAwait:
		return w.self.VisitAwait(node.(*parser.AwaitNode))

	case parser.ParseNodeTypeBinaryOperation:
		return w.self.VisitBinaryOperation(node.(*parser.BinaryOperationNode))

	case parser.ParseNodeTypeBreak:
		return w.self.VisitBreak(node.(*parser.BreakNode))

	case parser.ParseNodeTypeCall:
		return w.self.VisitCall(node.(*parser.CallNode))

	case parser.ParseNodeTypeCase:
		return w.self.VisitCase(node.(*parser.CaseNode))

	case parser.ParseNodeTypeClass:
		return w.self.VisitClass(node.(*parser.ClassNode))

	case parser.ParseNodeTypeComprehension:
		return w.self.VisitComprehension(node.(*parser.ComprehensionNode))

	case parser.ParseNodeTypeComprehensionFor:
		return w.self.VisitComprehensionFor(node.(*parser.ComprehensionForNode))

	case parser.ParseNodeTypeComprehensionIf:
		return w.self.VisitComprehensionIf(node.(*parser.ComprehensionIfNode))

	case parser.ParseNodeTypeConstant:
		return w.self.VisitConstant(node.(*parser.ConstantNode))

	case parser.ParseNodeTypeContinue:
		return w.self.VisitContinue(node.(*parser.ContinueNode))

	case parser.ParseNodeTypeDecorator:
		return w.self.VisitDecorator(node.(*parser.DecoratorNode))

	case parser.ParseNodeTypeDel:
		return w.self.VisitDel(node.(*parser.DelNode))

	case parser.ParseNodeTypeDictionary:
		return w.self.VisitDictionary(node.(*parser.DictionaryNode))

	case parser.ParseNodeTypeDictionaryExpandEntry:
		return w.self.VisitDictionaryExpandEntry(node.(*parser.DictionaryExpandEntryNode))

	case parser.ParseNodeTypeDictionaryKeyEntry:
		return w.self.VisitDictionaryKeyEntry(node.(*parser.DictionaryKeyEntryNode))

	case parser.ParseNodeTypeEllipsis:
		return w.self.VisitEllipsis(node.(*parser.EllipsisNode))

	case parser.ParseNodeTypeIf:
		return w.self.VisitIf(node.(*parser.IfNode))

	case parser.ParseNodeTypeImport:
		return w.self.VisitImport(node.(*parser.ImportNode))

	case parser.ParseNodeTypeImportAs:
		return w.self.VisitImportAs(node.(*parser.ImportAsNode))

	case parser.ParseNodeTypeImportFrom:
		return w.self.VisitImportFrom(node.(*parser.ImportFromNode))

	case parser.ParseNodeTypeImportFromAs:
		return w.self.VisitImportFromAs(node.(*parser.ImportFromAsNode))

	case parser.ParseNodeTypeIndex:
		return w.self.VisitIndex(node.(*parser.IndexNode))

	case parser.ParseNodeTypeExcept:
		return w.self.VisitExcept(node.(*parser.ExceptNode))

	case parser.ParseNodeTypeFor:
		return w.self.VisitFor(node.(*parser.ForNode))

	case parser.ParseNodeTypeFormatString:
		return w.self.VisitFormatString(node.(*parser.FormatStringNode))

	case parser.ParseNodeTypeFunction:
		return w.self.VisitFunction(node.(*parser.FunctionNode))

	case parser.ParseNodeTypeFunctionAnnotation:
		return w.self.VisitFunctionAnnotation(node.(*parser.FunctionAnnotationNode))

	case parser.ParseNodeTypeGlobal:
		return w.self.VisitGlobal(node.(*parser.GlobalNode))

	case parser.ParseNodeTypeLambda:
		return w.self.VisitLambda(node.(*parser.LambdaNode))

	case parser.ParseNodeTypeList:
		return w.self.VisitList(node.(*parser.ListNode))

	case parser.ParseNodeTypeMatch:
		return w.self.VisitMatch(node.(*parser.MatchNode))

	case parser.ParseNodeTypeMemberAccess:
		return w.self.VisitMemberAccess(node.(*parser.MemberAccessNode))

	case parser.ParseNodeTypeModuleName:
		return w.self.VisitModuleName(node.(*parser.ModuleNameNode))

	case parser.ParseNodeTypeModule:
		return w.self.VisitModule(node.(*parser.ModuleNode))

	case parser.ParseNodeTypeName:
		return w.self.VisitName(node.(*parser.NameNode))

	case parser.ParseNodeTypeNonlocal:
		return w.self.VisitNonlocal(node.(*parser.NonlocalNode))

	case parser.ParseNodeTypeNumber:
		return w.self.VisitNumber(node.(*parser.NumberNode))

	case parser.ParseNodeTypeParameter:
		return w.self.VisitParameter(node.(*parser.ParameterNode))

	case parser.ParseNodeTypePass:
		return w.self.VisitPass(node.(*parser.PassNode))

	case parser.ParseNodeTypePatternAs:
		return w.self.VisitPatternAs(node.(*parser.PatternAsNode))

	case parser.ParseNodeTypePatternClass:
		return w.self.VisitPatternClass(node.(*parser.PatternClassNode))

	case parser.ParseNodeTypePatternClassArgument:
		return w.self.VisitPatternClassArgument(node.(*parser.PatternClassArgumentNode))

	case parser.ParseNodeTypePatternCapture:
		return w.self.VisitPatternCapture(node.(*parser.PatternCaptureNode))

	case parser.ParseNodeTypePatternLiteral:
		return w.self.VisitPatternLiteral(node.(*parser.PatternLiteralNode))

	case parser.ParseNodeTypePatternMappingExpandEntry:
		return w.self.VisitPatternMappingExpandEntry(node.(*parser.PatternMappingExpandEntryNode))

	case parser.ParseNodeTypePatternMappingKeyEntry:
		return w.self.VisitPatternMappingKeyEntry(node.(*parser.PatternMappingKeyEntryNode))

	case parser.ParseNodeTypePatternMapping:
		return w.self.VisitPatternMapping(node.(*parser.PatternMappingNode))

	case parser.ParseNodeTypePatternSequence:
		return w.self.VisitPatternSequence(node.(*parser.PatternSequenceNode))

	case parser.ParseNodeTypePatternValue:
		return w.self.VisitPatternValue(node.(*parser.PatternValueNode))

	case parser.ParseNodeTypeRaise:
		return w.self.VisitRaise(node.(*parser.RaiseNode))

	case parser.ParseNodeTypeReturn:
		return w.self.VisitReturn(node.(*parser.ReturnNode))

	case parser.ParseNodeTypeSet:
		return w.self.VisitSet(node.(*parser.SetNode))

	case parser.ParseNodeTypeSlice:
		return w.self.VisitSlice(node.(*parser.SliceNode))

	case parser.ParseNodeTypeStatementList:
		return w.self.VisitStatementList(node.(*parser.StatementListNode))

	case parser.ParseNodeTypeStringList:
		return w.self.VisitStringList(node.(*parser.StringListNode))

	case parser.ParseNodeTypeString:
		return w.self.VisitString(node.(*parser.StringNode))

	case parser.ParseNodeTypeSuite:
		return w.self.VisitSuite(node.(*parser.SuiteNode))

	case parser.ParseNodeTypeTernary:
		return w.self.VisitTernary(node.(*parser.TernaryNode))

	case parser.ParseNodeTypeTuple:
		return w.self.VisitTuple(node.(*parser.TupleNode))

	case parser.ParseNodeTypeTry:
		return w.self.VisitTry(node.(*parser.TryNode))

	case parser.ParseNodeTypeTypeAlias:
		return w.self.VisitTypeAlias(node.(*parser.TypeAliasNode))

	case parser.ParseNodeTypeTypeAnnotation:
		return w.self.VisitTypeAnnotation(node.(*parser.TypeAnnotationNode))

	case parser.ParseNodeTypeTypeParameter:
		return w.self.VisitTypeParameter(node.(*parser.TypeParameterNode))

	case parser.ParseNodeTypeTypeParameterList:
		return w.self.VisitTypeParameterList(node.(*parser.TypeParameterListNode))

	case parser.ParseNodeTypeUnaryOperation:
		return w.self.VisitUnaryOperation(node.(*parser.UnaryOperationNode))

	case parser.ParseNodeTypeUnpack:
		return w.self.VisitUnpack(node.(*parser.UnpackNode))

	case parser.ParseNodeTypeWhile:
		return w.self.VisitWhile(node.(*parser.WhileNode))

	case parser.ParseNodeTypeWith:
		return w.self.VisitWith(node.(*parser.WithNode))

	case parser.ParseNodeTypeWithItem:
		return w.self.VisitWithItem(node.(*parser.WithItemNode))

	case parser.ParseNodeTypeYield:
		return w.self.VisitYield(node.(*parser.YieldNode))

	case parser.ParseNodeTypeYieldFrom:
		return w.self.VisitYieldFrom(node.(*parser.YieldFromNode))

	}

	common.Fail("Unknown parse node type")
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitError(node *parser.ErrorNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitArgument(node *parser.ArgumentNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitAssert(node *parser.AssertNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitAssignmentExpression(node *parser.AssignmentExpressionNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitAssignment(node *parser.AssignmentNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitAugmentedAssignment(node *parser.AugmentedAssignmentNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitAwait(node *parser.AwaitNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitBinaryOperation(node *parser.BinaryOperationNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitBreak(node *parser.BreakNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitCall(node *parser.CallNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitCase(node *parser.CaseNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitClass(node *parser.ClassNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitComprehension(node *parser.ComprehensionNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitComprehensionFor(node *parser.ComprehensionForNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitComprehensionIf(node *parser.ComprehensionIfNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitConstant(node *parser.ConstantNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitContinue(node *parser.ContinueNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitDecorator(node *parser.DecoratorNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitDel(node *parser.DelNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitDictionary(node *parser.DictionaryNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitDictionaryExpandEntry(node *parser.DictionaryExpandEntryNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitDictionaryKeyEntry(node *parser.DictionaryKeyEntryNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitEllipsis(node *parser.EllipsisNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitIf(node *parser.IfNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitImport(node *parser.ImportNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitImportAs(node *parser.ImportAsNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitImportFrom(node *parser.ImportFromNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitImportFromAs(node *parser.ImportFromAsNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitIndex(node *parser.IndexNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitExcept(node *parser.ExceptNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitFor(node *parser.ForNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitFormatString(node *parser.FormatStringNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitFunction(node *parser.FunctionNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitFunctionAnnotation(node *parser.FunctionAnnotationNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitGlobal(node *parser.GlobalNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitLambda(node *parser.LambdaNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitList(node *parser.ListNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitMatch(node *parser.MatchNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitMemberAccess(node *parser.MemberAccessNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitModuleName(node *parser.ModuleNameNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitModule(node *parser.ModuleNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitName(node *parser.NameNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitNonlocal(node *parser.NonlocalNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitNumber(node *parser.NumberNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitParameter(node *parser.ParameterNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitPass(node *parser.PassNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitPatternAs(node *parser.PatternAsNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitPatternClass(node *parser.PatternClassNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternClassArgument(node *parser.PatternClassArgumentNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternCapture(node *parser.PatternCaptureNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternLiteral(node *parser.PatternLiteralNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternMappingExpandEntry(node *parser.PatternMappingExpandEntryNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternMappingKeyEntry(node *parser.PatternMappingKeyEntryNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternMapping(node *parser.PatternMappingNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternSequence(node *parser.PatternSequenceNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitPatternValue(node *parser.PatternValueNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitRaise(node *parser.RaiseNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitReturn(node *parser.ReturnNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitSet(node *parser.SetNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitSlice(node *parser.SliceNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitStatementList(node *parser.StatementListNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitStringList(node *parser.StringListNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitString(node *parser.StringNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitSuite(node *parser.SuiteNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitTernary(node *parser.TernaryNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitTuple(node *parser.TupleNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitTry(node *parser.TryNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitTypeAlias(node *parser.TypeAliasNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitTypeAnnotation(node *parser.TypeAnnotationNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitTypeParameter(node *parser.TypeParameterNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitTypeParameterList(node *parser.TypeParameterListNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitUnaryOperation(node *parser.UnaryOperationNode) bool {
	return w.defaultValue
}

func (w *ParseTreeWalker) VisitUnpack(node *parser.UnpackNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitWhile(node *parser.WhileNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitWith(node *parser.WithNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitWithItem(node *parser.WithItemNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitYield(node *parser.YieldNode) bool { return w.defaultValue }

func (w *ParseTreeWalker) VisitYieldFrom(node *parser.YieldFromNode) bool { return w.defaultValue }
